from __future__ import annotations

import hashlib
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    roots = (
        root / "src" / "crossres_pred",
        root / "provenance" / "source",
        root / "native" / "line_fitter" / "src",
        root / "native" / "line_fitter" / "third_party",
    )
    files = sorted(
        path
        for source in roots
        for path in source.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    )
    lines = [
        "# SHA-256 source snapshot manifest; generated by scripts/build_source_manifest.py",
        *(f"{sha256(path)}  {path.relative_to(root).as_posix()}" for path in files),
    ]
    destination = root / "provenance" / "SHA256SUMS"
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {destination} with {len(files)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
